# Generated by Django 3.0.1 on 2019-12-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.TextField(default='anonymous')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('date', models.DateField()),
            ],
        ),
    ]
