# Generated by Django 3.0.1 on 2020-01-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20200103_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donor_name',
        ),
        migrations.AddField(
            model_name='donation',
            name='cc_expiration',
            field=models.CharField(default='MM/YYYY', max_length=10),
        ),
        migrations.AddField(
            model_name='donation',
            name='cc_num',
            field=models.IntegerField(default=123412412341234),
        ),
        migrations.AddField(
            model_name='donation',
            name='ccv_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donation',
            name='first_name',
            field=models.CharField(default='Required', max_length=50),
        ),
        migrations.AddField(
            model_name='donation',
            name='last_name',
            field=models.CharField(default='Required', max_length=50),
        ),
        migrations.AddField(
            model_name='donation',
            name='phone_number',
            field=models.IntegerField(default=1234567890),
        ),
    ]
