# Generated by Django 3.0.1 on 2020-01-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_auto_20200107_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
