# Generated by Django 3.0.1 on 2020-01-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_auto_20200109_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
    ]
